import "./coverage";
import { expect, test, type Page } from '@playwright/test';
async function signIn(page:Page,role:string){await page.goto('/login');await page.getByLabel('Email').fill(`${role.toLowerCase()}@example.test`);await page.getByLabel('Password').fill('Test-password1!');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('button',{name:'Sign out'})).toBeVisible();}
async function signOut(page:Page){await page.getByRole('button',{name:'Sign out'}).click();await expect(page.getByRole('button',{name:'Sign in',exact:true})).toBeVisible();}
test('all four roles complete an internship and a report revision through the UI',async({page})=>{
 await signIn(page,'COMPANY_STAFF');await page.getByRole('link',{name:'Create draft'}).click();await page.getByRole('combobox',{name:/^Company/}).selectOption({label:'Browser Test Company'});await page.getByLabel('Title').fill('Browser Internship');await page.getByLabel('Duration weeks').fill('12');await page.getByLabel('Openings').fill('1');await page.getByLabel('Deadline').fill('2099-12-31');await page.getByLabel('Description').fill('Engineering internship');await page.getByLabel('Required skills').fill('TypeScript');await page.getByRole('button',{name:'Create draft',exact:true}).click();await page.getByRole('button',{name:'Publish',exact:true}).click();await expect(page.getByRole('button',{name:'Close',exact:true})).toBeVisible();await signOut(page);
 await signIn(page,'STUDENT');await page.getByRole('link',{name:'Profile',exact:true}).click();await page.getByLabel('Skills').fill('TypeScript | ADVANCED');await page.getByRole('button',{name:'Save skills'}).click();await page.getByLabel('Upload document').setInputFiles({name:'cv.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-browser-test')});await expect(page.getByText(/AVAILABLE/)).toBeVisible();await page.getByRole('link',{name:'Discover',exact:true}).click();await page.getByRole('link',{name:'View posting'}).click();await page.getByRole('button',{name:'Apply',exact:true}).click();
 for(const [label,value] of Object.entries({'Contact name':'Student','Contact email':'student@example.test','University':'University','Major':'CS','Availability':'Now','Cover note':'Ready to learn'}))await page.getByLabel(label).fill(value);
 await page.getByLabel('CV').selectOption({label:'cv.pdf'});await page.getByRole('button',{name:'Submit application'}).click();await expect(page.getByRole('heading',{name:'Application detail'})).toBeVisible();await signOut(page);
 await signIn(page,'COMPANY_STAFF');await page.getByRole('link',{name:'Applications',exact:true}).click();await page.getByRole('link',{name:'Open',exact:true}).click();await page.getByRole('button',{name:'Start review'}).click();await page.getByRole('button',{name:'Move to interview'}).click();await page.getByRole('button',{name:'Accept and create placement'}).click();await page.getByLabel('Start date').fill('2026-09-14');await page.getByLabel('End date').fill('2026-12-31');await page.getByRole('button',{name:'Accept',exact:true}).click();await expect(page.getByRole('heading',{name:'Weekly reports'})).toBeVisible();await signOut(page);
 await signIn(page,'SUPERVISOR');await page.getByRole('link',{name:/Placement 2026/}).click();await page.getByRole('button',{name:'Assign task'}).click();await page.getByLabel('Title').fill('Write tests');await page.getByLabel('Description').fill('Cover the happy path');await page.getByRole('button',{name:'Create task'}).click();await expect(page.getByText('Task created.')).toBeVisible();await signOut(page);
 await signIn(page,'STUDENT');await page.getByRole('link',{name:'Placements',exact:true}).click();await page.getByRole('link',{name:/Placement 2026/}).click();await page.getByLabel('Status for Write tests').selectOption('DONE');await page.getByRole('link',{name:'Weekly reports'}).click();await page.getByRole('button',{name:'Start',exact:true}).first().click();await page.getByLabel('Accomplishments').fill('Implemented tests');await page.getByLabel('Challenges').fill('Learning SQL');await page.getByLabel('Next-week plan').fill('Improve coverage');await page.getByRole('button',{name:'Save draft'}).click();await page.getByRole('button',{name:'Submit saved draft'}).click();await expect(page.getByText('SUBMITTED',{exact:true})).toBeVisible();await signOut(page);
 await signIn(page,'SUPERVISOR');await page.getByRole('link',{name:/Placement 2026/}).click();await page.getByRole('link',{name:'Weekly reports'}).click();await page.getByRole('link',{name:'Open',exact:true}).click();await page.getByLabel('Review feedback').fill('Add concrete results');await page.getByRole('button',{name:'Request revision'}).click();await expect(page.getByText('REVISION_REQUESTED',{exact:true})).toBeVisible();await signOut(page);
 await signIn(page,'STUDENT');await page.getByRole('link',{name:'Placements',exact:true}).click();await page.getByRole('link',{name:/Placement 2026/}).click();await page.getByRole('link',{name:'Weekly reports'}).click();await page.getByRole('link',{name:'Open',exact:true}).click();await page.getByLabel('Accomplishments').fill('Implemented 12 passing tests');await page.getByRole('button',{name:'Save draft'}).click();await expect(page.getByText('Draft saved.')).toBeVisible();await page.getByRole('button',{name:'Submit saved draft'}).click();await expect(page.getByLabel('Report version').locator('option')).toHaveCount(2);await signOut(page);
 await signIn(page,'ADMIN');await expect(page.getByRole('heading',{name:'Monitoring'})).toBeVisible();await page.getByRole('link',{name:'Placements',exact:true}).click();await page.getByRole('link',{name:/Placement 2026/}).click();await page.getByRole('link',{name:'Performance evaluation'}).click();await page.getByLabel('Completion decision').selectOption('PASSED');await page.getByRole('button',{name:'Submit',exact:true}).click();await page.getByRole('link',{name:'Placements',exact:true}).click();await page.getByRole('link',{name:/Placement 2026/}).click();await page.getByRole('button',{name:'Complete placement'}).click();await expect(page.getByText(/COMPLETED/)).toBeVisible();
});
