import { BadRequestException, Body, ConflictException, Controller, Delete, Get, NotFoundException, Param, Patch, Post, Put, Query, Req, Res, StreamableFile } from '@nestjs/common';
import { Cron } from '@nestjs/schedule';
import { InjectRepository } from '@nestjs/typeorm';
import { JwtService } from '@nestjs/jwt';
import { createHash, randomUUID } from 'node:crypto';
import type { Request, Response } from 'express';
import { In, Repository } from 'typeorm';
import { AiJob, Application, AuditEvent, Company, Document, Notification, PerformanceEvaluation, Placement, ReportDraftDocument, ReportReview, ReportVersion, ReportVersionDocument, ReportingPeriod, SelfAssessment, StudentDocument, SupervisorAssignment, SupervisorProfile, User, WeeklyReport } from '../infrastructure/database/entities';
import { CurrentUser, Principal, Roles, assert } from './auth';
import { PrivateStorageService } from './private-storage.service';
import { reportingPeriods } from './calendar';

const MAX_FILE = 10 * 1024 * 1024;
const trim = (value?: string) => value?.trim() || undefined;
const page = (n?: string) => Math.max(1, Number(n ?? 1) || 1);
const size = (n?: string) => Math.min(100, Math.max(1, Number(n ?? 20) || 20));
const validRatings = (ratings: unknown, required: boolean) => typeof ratings === 'object' && ratings !== null && (!required || Object.keys(ratings as object).length > 0) && Object.values(ratings as object).every((x) => Number.isInteger(x) && Number(x) >= 1 && Number(x) <= 5);
const canonical = (value: unknown): string => Array.isArray(value) ? `[${value.map(canonical).join(',')}]` : value && typeof value === 'object' ? `{${Object.keys(value as object).sort().map((k) => `${JSON.stringify(k)}:${canonical((value as Record<string, unknown>)[k])}`).join(',')}}` : JSON.stringify(value);

@Controller()
export class AdvancedController {
  constructor(
    @InjectRepository(User) private users: Repository<User>, @InjectRepository(Company) private companies: Repository<Company>, @InjectRepository(Application) private applications: Repository<Application>, @InjectRepository(Placement) private placements: Repository<Placement>, @InjectRepository(Notification) private notifications: Repository<Notification>, @InjectRepository(Document) private documents: Repository<Document>, @InjectRepository(StudentDocument) private studentDocuments: Repository<StudentDocument>, @InjectRepository(SupervisorProfile) private supervisorProfiles: Repository<SupervisorProfile>, @InjectRepository(SupervisorAssignment) private assignments: Repository<SupervisorAssignment>, @InjectRepository(ReportingPeriod) private periods: Repository<ReportingPeriod>, @InjectRepository(WeeklyReport) private reports: Repository<WeeklyReport>, @InjectRepository(ReportVersion) private versions: Repository<ReportVersion>, @InjectRepository(ReportReview) private reviews: Repository<ReportReview>, @InjectRepository(ReportDraftDocument) private draftDocs: Repository<ReportDraftDocument>, @InjectRepository(ReportVersionDocument) private versionDocs: Repository<ReportVersionDocument>, @InjectRepository(SelfAssessment) private selfAssessments: Repository<SelfAssessment>, @InjectRepository(PerformanceEvaluation) private evaluations: Repository<PerformanceEvaluation>, @InjectRepository(AuditEvent) private audit: Repository<AuditEvent>, @InjectRepository(AiJob) private jobs: Repository<AiJob>, private storage: PrivateStorageService, private jwt: JwtService) {}

  @Get('supervisors') @Roles('COMPANY_STAFF', 'ADMIN') async supervisors(@CurrentUser() p: Principal, @Query() query: { applicationId?: string; placementId?: string; search?: string; page?: string; pageSize?: string }) {
    if (Boolean(query.applicationId) === Boolean(query.placementId)) throw new BadRequestException('Supply exactly one applicationId or placementId');
    if (query.placementId) assert(p.role === 'ADMIN');
    if (query.applicationId && p.role !== 'ADMIN') { const app = await this.applications.findOneBy({ id: query.applicationId }); if (!app) throw new NotFoundException(); await this.companyAccess(p, (await this.placements.findOneBy({ applicationId: app.id }))?.companyId); }
    const profiles = await this.supervisorProfiles.find(); const users = await this.users.findBy({ id: In(profiles.map((x) => x.userId)) }); const search = query.search?.toLocaleLowerCase() ?? ''; const items = users.filter((u) => u.roles.includes('SUPERVISOR') && u.fullName.toLocaleLowerCase().includes(search)).map((u) => ({ id: u.id, fullName: u.fullName, department: profiles.find((x) => x.userId === u.id)?.department })); return this.paginate(items, query.page, query.pageSize);
  }
  @Get('placements/:placementId/supervisor-assignments') @Roles('ADMIN') async assignmentHistory(@Param('placementId') id: string) { return this.assignments.find({ where: { placementId: id }, order: { assignedAt: 'ASC' } }); }
  @Put('placements/:placementId/supervisor-assignments') @Roles('ADMIN') async changeAssignment(@CurrentUser() p: Principal, @Param('placementId') id: string, @Body() body: { expectedAssignmentId?: string | null; supervisorUserId?: string | null; reason?: string }) {
    const placement = await this.placements.findOneBy({ id }); if (!placement) throw new NotFoundException(); if (placement.status !== 'ACTIVE' || !trim(body.reason)) throw new ConflictException('Active placement and reason required'); const active = await this.assignments.findOneBy({ placementId: id, revokedAt: null as any }); if ((active?.id ?? null) !== (body.expectedAssignmentId ?? null)) throw new ConflictException('ASSIGNMENT_CONFLICT'); if (active?.supervisorUserId === body.supervisorUserId) return placement;
    if (body.supervisorUserId) await this.assertSupervisor(body.supervisorUserId); if (active) await this.assignments.update(active.id, { revokedAt: new Date(), revokedByUserId: p.id, revocationReason: trim(body.reason) }); if (body.supervisorUserId) await this.assignments.save({ placementId: id, supervisorUserId: body.supervisorUserId, assignedByUserId: p.id, reason: trim(body.reason) }); await this.audit.save({ subjectType: 'PLACEMENT', subjectId: id, eventType: 'SUPERVISOR_ASSIGNMENT_CHANGED', actorUserId: p.id, payload: {} }); return placement;
  }
  @Get('placements/:placementId/reporting-periods') async listPeriods(@CurrentUser() p: Principal, @Param('placementId') id: string) { await this.placementAccess(p, id); return this.periods.find({ where: { placementId: id }, order: { weekStart: 'ASC' } }); }

  @Get('documents') @Roles('STUDENT') async listDocuments(@CurrentUser() p: Principal) { const links = await this.studentDocuments.findBy({ studentId: p.id }); return { items: await this.documents.findBy({ id: In(links.map((x) => x.documentId)) }) }; }
  @Post('documents') @Roles('STUDENT') async beginDocument(@CurrentUser() p: Principal, @Body() body: { originalName: string; contentType: string; sizeBytes: number; sha256: string; kind?: string }) {
    if (!trim(body.originalName) || !['application/pdf', 'image/jpeg', 'image/png', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'].includes(body.contentType) || !Number.isInteger(body.sizeBytes) || body.sizeBytes < 1 || body.sizeBytes > MAX_FILE || !/^[a-f0-9]{64}$/i.test(body.sha256 ?? '')) throw new BadRequestException('Invalid document metadata');
    const doc = await this.documents.save({ ownerUserId: p.id, objectKey: `documents/${p.id}/${randomUUID()}`, originalName: body.originalName.trim(), contentType: body.contentType, sizeBytes: String(body.sizeBytes), sha256: body.sha256.toLowerCase(), state: 'PENDING' }); await this.studentDocuments.save({ studentId: p.id, documentId: doc.id, kind: body.kind ?? 'OTHER' }); const token = await this.jwt.signAsync({ sid: p.sid, documentId: doc.id, method: 'PUT', size: body.sizeBytes, sha256: doc.sha256, contentType: doc.contentType }, { secret: process.env.UPLOAD_TOKEN_SECRET ?? process.env.JWT_SECRET }); return { document: this.documentDto(doc), uploadUrl: `/api/v1/documents/${doc.id}/content?transferToken=${token}`, expiresAt: new Date(Date.now() + 300000) };
  }
  @Put('documents/:documentId/content') @Roles('STUDENT') async uploadDocument(@CurrentUser() p: Principal, @Param('documentId') id: string, @Query('transferToken') token: string, @Req() req: Request) {
    const doc = await this.documents.findOneBy({ id, ownerUserId: p.id }); if (!doc || doc.state !== 'PENDING') throw new ConflictException('Document is not uploadable'); let claim: any; try { claim = await this.jwt.verifyAsync(token, { secret: process.env.UPLOAD_TOKEN_SECRET ?? process.env.JWT_SECRET }); } catch { throw new BadRequestException('Invalid transfer token'); } if (claim.sid !== p.sid || claim.documentId !== id || claim.method !== 'PUT' || claim.size !== Number(doc.sizeBytes) || claim.sha256 !== doc.sha256 || claim.contentType !== doc.contentType) throw new BadRequestException('Transfer token does not match document'); const chunks: Buffer[] = []; let total = 0; for await (const c of req) { total += c.length; if (total > MAX_FILE) throw new BadRequestException('File too large'); chunks.push(Buffer.from(c)); } const bytes = Buffer.concat(chunks); if (bytes.length !== Number(doc.sizeBytes) || createHash('sha256').update(bytes).digest('hex') !== doc.sha256 || !signatureMatches(bytes, doc.contentType)) throw new BadRequestException('Bytes do not match declared document'); await this.storage.put(doc.objectKey, bytes, doc.contentType); return;
  }
  @Post('documents/:documentId/complete') @Roles('STUDENT') async completeDocument(@CurrentUser() p: Principal, @Param('documentId') id: string) { const doc = await this.documents.findOneBy({ id, ownerUserId: p.id }); if (!doc) throw new NotFoundException(); if (doc.state === 'AVAILABLE') return this.documentDto(doc); if (doc.state !== 'PENDING') throw new ConflictException('Document rejected'); try { const stat = await this.storage.stat(doc.objectKey); if (Number(stat.size) !== Number(doc.sizeBytes)) throw new Error('size'); doc.state = 'AVAILABLE'; } catch { doc.state = 'REJECTED'; } return this.documentDto(await this.documents.save(doc)); }
  @Delete('documents/:documentId') @Roles('STUDENT') async deleteDocument(@CurrentUser() p: Principal, @Param('documentId') id: string) { const doc = await this.documents.findOneBy({ id, ownerUserId: p.id }); if (!doc) throw new NotFoundException(); if ((await this.draftDocs.countBy({ documentId: id })) || (await this.versionDocs.countBy({ documentId: id }))) throw new ConflictException('Document is retained'); doc.state = 'DELETED'; await this.documents.save(doc); await this.storage.remove(doc.objectKey).catch(() => undefined); return; }
  @Get('documents/:documentId/download-url') async downloadUrl(@CurrentUser() p: Principal, @Param('documentId') id: string) { await this.documentAccess(p, id); const token = await this.jwt.signAsync({ sid: p.sid, documentId: id, method: 'GET' }, { secret: process.env.UPLOAD_TOKEN_SECRET ?? process.env.JWT_SECRET }); return { url: `/api/v1/documents/${id}/content?transferToken=${token}`, expiresAt: new Date(Date.now() + 300000) }; }
  @Get('documents/:documentId/content') async downloadDocument(@CurrentUser() p: Principal, @Param('documentId') id: string, @Query('transferToken') token: string, @Res({ passthrough: true }) res: Response) { const doc = await this.documentAccess(p, id); try { const claim: any = await this.jwt.verifyAsync(token, { secret: process.env.UPLOAD_TOKEN_SECRET ?? process.env.JWT_SECRET }); if (claim.sid !== p.sid || claim.documentId !== id || claim.method !== 'GET') throw new Error(); } catch { throw new BadRequestException('Invalid transfer token'); } res.set({ 'Content-Type': doc.contentType, 'Content-Disposition': `attachment; filename="${doc.originalName.replace(/[\\\"]/g, '_')}"`, 'Cache-Control': 'private, no-store' }); return new StreamableFile(await this.storage.get(doc.objectKey)); }

  @Get('placements/:placementId/reports') async listReports(@CurrentUser() p: Principal, @Param('placementId') placementId: string) { const placement = await this.placementAccess(p, placementId); const rows = await this.reports.findBy({ placementId }); return Promise.all(rows.filter((r) => p.role === 'STUDENT' || r.currentVersionNo > 0).map((r) => this.reportDto(r, placement, p.role === 'STUDENT' && placement.studentId === p.id))); }
  @Post('placements/:placementId/reports') @Roles('STUDENT') async createDraft(@CurrentUser() p: Principal, @Param('placementId') placementId: string, @Body() body: any) { const placement = await this.placementAccess(p, placementId); assert(placement.studentId === p.id && placement.status === 'ACTIVE'); const period = await this.periods.findOneBy({ id: body.reportingPeriodId, placementId }); if (!period || period.weekStart > new Date().toISOString().slice(0, 10)) throw new ConflictException('Invalid reporting period'); let report = await this.reports.findOneBy({ reportingPeriodId: period.id }); if (!report) report = await this.reports.save({ placementId, reportingPeriodId: period.id, state: 'DRAFT', currentVersionNo: 0 }); return this.saveDraft(report, body, p, placement); }
  @Get('reports/:reportId') async getReport(@CurrentUser() p: Principal, @Param('reportId') id: string) { const report = await this.reports.findOneBy({ id }); if (!report) throw new NotFoundException(); const placement = await this.placementAccess(p, report.placementId); if (p.role !== 'STUDENT' && report.currentVersionNo === 0) throw new NotFoundException(); return this.reportDto(report, placement, p.role === 'STUDENT' && placement.studentId === p.id); }
  @Patch('reports/:reportId') @Roles('STUDENT') async patchReport(@CurrentUser() p: Principal, @Param('reportId') id: string, @Body() body: any) { const report = await this.reports.findOneBy({ id }); if (!report) throw new NotFoundException(); const placement = await this.placementAccess(p, report.placementId); assert(placement.studentId === p.id && placement.status === 'ACTIVE' && ['DRAFT', 'REVISION_REQUESTED'].includes(report.state)); return this.saveDraft(report, body, p, placement); }
  @Post('reports/:reportId/submit') @Roles('STUDENT') async submitReport(@CurrentUser() p: Principal, @Param('reportId') id: string) { const report = await this.reports.findOneBy({ id }); if (!report) throw new NotFoundException(); const placement = await this.placementAccess(p, report.placementId); assert(placement.studentId === p.id && placement.status === 'ACTIVE' && ['DRAFT', 'REVISION_REQUESTED'].includes(report.state)); const a = trim(report.draftAccomplishments), c = trim(report.draftChallenges), n = trim(report.draftNextWeekPlan); if (!a || !c || !n) throw new BadRequestException('All report fields are required'); const version = await this.versions.save({ reportId: id, versionNo: report.currentVersionNo + 1, accomplishments: a, challenges: c, nextWeekPlan: n, submittedByUserId: p.id }); const links = await this.draftDocs.findBy({ reportId: id }); if (links.length) await this.versionDocs.save(links.map((x) => ({ reportVersionId: version.id, documentId: x.documentId }))); await this.draftDocs.delete({ reportId: id }); Object.assign(report, { state: 'SUBMITTED', currentVersionNo: version.versionNo, draftAccomplishments: undefined, draftChallenges: undefined, draftNextWeekPlan: undefined, draftSavedAt: undefined }); return this.reportDto(await this.reports.save(report), placement, true); }
  @Post('reports/:reportId/reviews') @Roles('SUPERVISOR', 'ADMIN') async reviewReport(@CurrentUser() p: Principal, @Param('reportId') id: string, @Body() body: { reportVersionId: string; outcome: 'APPROVED' | 'REVISION_REQUESTED'; feedback?: string }) { const report = await this.reports.findOneBy({ id }); if (!report) throw new NotFoundException(); const placement = await this.placementAccess(p, report.placementId); if (placement.status !== 'ACTIVE' || report.state !== 'SUBMITTED') throw new ConflictException('REPORT_VERSION_CONFLICT'); const version = await this.versions.findOneBy({ id: body.reportVersionId, reportId: id, versionNo: report.currentVersionNo }); if (!version || await this.reviews.findOneBy({ reportVersionId: body.reportVersionId })) throw new ConflictException('REPORT_VERSION_CONFLICT'); if (!['APPROVED', 'REVISION_REQUESTED'].includes(body.outcome) || (body.outcome === 'REVISION_REQUESTED' && !trim(body.feedback))) throw new BadRequestException('Feedback is required for revision'); await this.reviews.save({ reportVersionId: version.id, outcome: body.outcome, feedback: trim(body.feedback), reviewedByUserId: p.id }); report.state = body.outcome; await this.reports.save(report); await this.notifications.save({ recipientUserId: placement.studentId, type: body.outcome === 'APPROVED' ? 'REPORT_FEEDBACK' : 'REPORT_REVISION_REQUESTED', title: 'Report reviewed', targetType: 'REPORT', targetId: id }); return this.reportDto(report, placement, false); }

  @Get('placements/:placementId/self-assessment') @Roles('STUDENT') async getSelf(@CurrentUser() p: Principal, @Param('placementId') id: string) { const placement = await this.placementAccess(p, id); assert(placement.studentId === p.id); const row = await this.selfAssessments.findOneBy({ placementId: id }); if (!row) throw new NotFoundException(); return row; }
  @Put('placements/:placementId/self-assessment') @Roles('STUDENT') async putSelf(@CurrentUser() p: Principal, @Param('placementId') id: string, @Body() body: any) { const placement = await this.placementAccess(p, id); assert(placement.studentId === p.id); if (!['DRAFT', 'SUBMITTED'].includes(body.status) || !validRatings(body.ratings ?? {}, body.status === 'SUBMITTED') || (body.status === 'SUBMITTED' && (!trim(body.reflection) || !trim(body.learningOutcomes)))) throw new BadRequestException('Invalid assessment'); let row = await this.selfAssessments.findOneBy({ placementId: id }); row = Object.assign(row ?? this.selfAssessments.create({ placementId: id }), { status: body.status, ratings: body.ratings ?? {}, reflection: trim(body.reflection), learningOutcomes: trim(body.learningOutcomes), submittedAt: body.status === 'SUBMITTED' ? new Date() : undefined }); return this.selfAssessments.save(row); }
  @Get('placements/:placementId/performance-evaluation') @Roles('SUPERVISOR', 'ADMIN') async getEvaluation(@CurrentUser() p: Principal, @Param('placementId') id: string) { await this.placementAccess(p, id); const row = await this.evaluations.findOneBy({ placementId: id }); if (!row) throw new NotFoundException(); return row; }
  @Put('placements/:placementId/performance-evaluation') @Roles('SUPERVISOR', 'ADMIN') async putEvaluation(@CurrentUser() p: Principal, @Param('placementId') id: string, @Body() body: any) { await this.placementAccess(p, id); if (!['DRAFT', 'SUBMITTED'].includes(body.status) || !['PASSED', 'FAILED', 'PENDING', 'INCOMPLETE'].includes(body.completionDecision) || !validRatings(body.ratings ?? {}, body.status === 'SUBMITTED')) throw new BadRequestException('Invalid evaluation'); let row = await this.evaluations.findOneBy({ placementId: id }); if (row && row.authorUserId !== p.id && p.role !== 'ADMIN') throw new ConflictException('Evaluation author mismatch'); row = Object.assign(row ?? this.evaluations.create({ placementId: id, authorUserId: p.id }), { status: body.status, ratings: body.ratings ?? {}, comments: trim(body.comments), completionDecision: body.completionDecision, submittedAt: body.status === 'SUBMITTED' ? new Date() : undefined }); return this.evaluations.save(row); }

  @Get('monitoring') @Roles('ADMIN') async monitoring(@Query() scope: { programId?: string; termId?: string }) { const [apps, places, tasks, reports, periods, activity] = await Promise.all([this.applications.find(), this.placements.find(), this.audit.find({ order: { occurredAt: 'DESC' }, take: 20 }), this.reports.find(), this.periods.find(), this.audit.find({ order: { occurredAt: 'DESC' }, take: 20 })]); return { scope, applications: countBy(apps, 'status'), placements: countBy(places, 'status'), tasks: {}, reports: countBy(reports, 'state'), deadlines: periods.map((x) => ({ kind: 'REPORT', dueDate: x.weekEnd, dueAt: x.dueAt, timezone: 'Asia/Ho_Chi_Minh', reportingPeriodId: x.id, target: { type: 'PLACEMENT', id: x.placementId } })), recentActivity: activity.map((x) => ({ type: x.eventType, occurredAt: x.occurredAt, target: { type: x.subjectType, id: x.subjectId } })), readOnly: true }; }
  @Post('ai-jobs') async createAiJob(@CurrentUser() p: Principal, @Body() body: { kind: 'MATCH_EXPLANATION' | 'REPORT_SUMMARY'; postingId?: string; reportVersionId?: string }) { if ((body.kind === 'MATCH_EXPLANATION') === Boolean(body.reportVersionId) || (body.kind === 'REPORT_SUMMARY') === Boolean(body.postingId)) throw new BadRequestException('Invalid AI source'); let snapshot: object; if (body.kind === 'MATCH_EXPLANATION') { assert(p.role === 'STUDENT'); snapshot = { kind: body.kind, postingId: body.postingId, calculationVersion: 'skill-v1' }; } else { if (!body.reportVersionId) throw new BadRequestException(); const version = await this.versions.findOneBy({ id: body.reportVersionId }); if (!version) throw new NotFoundException(); const report = await this.reports.findOneByOrFail({ id: version.reportId }); await this.placementAccess(p, report.placementId); snapshot = { kind: body.kind, reportVersionId: version.id, accomplishments: version.accomplishments, challenges: version.challenges, nextWeekPlan: version.nextWeekPlan }; } const fingerprint = createHash('sha256').update(canonical(snapshot)).digest('hex'); let job = await this.jobs.findOneBy({ requestedByUserId: p.id, kind: body.kind, inputFingerprint: fingerprint, promptVersion: 'v1' }); if (!job || job.status === 'FAILED') job = await this.jobs.save({ requestedByUserId: p.id, kind: body.kind, postingId: body.postingId, reportVersionId: body.reportVersionId, inputFingerprint: fingerprint, inputSnapshot: snapshot, promptVersion: 'v1', status: 'PENDING', attempts: 0, availableAt: new Date() }); return this.jobDto(job, p); }
  @Get('ai-jobs/:aiJobId') async getAiJob(@CurrentUser() p: Principal, @Param('aiJobId') id: string) { const job = await this.jobs.findOneBy({ id, requestedByUserId: p.id }); if (!job) throw new NotFoundException(); if (job.reportVersionId) { const version = await this.versions.findOneBy({ id: job.reportVersionId }); if (version) await this.placementAccess(p, (await this.reports.findOneByOrFail({ id: version.reportId })).placementId); } return this.jobDto(job, p); }

  @Cron('0 * * * * *') async scanDeadlines() { const now = new Date(); const periods = await this.periods.find(); for (const period of periods) { const placement = await this.placements.findOneBy({ id: period.placementId }); if (!placement || placement.status !== 'ACTIVE') continue; const submitted = await this.reports.createQueryBuilder('r').where('r.reporting_period_id = :id AND r.current_version_no > 0', { id: period.id }).getExists(); const ms = period.dueAt.getTime() - now.getTime(); if (!submitted && ms <= 86400000) { const overdue = ms <= 0; const key = `${placement.studentId}:${period.id}:${overdue ? 'REPORT_OVERDUE' : 'REPORT_DUE'}`; try { await this.notifications.save({ recipientUserId: placement.studentId, type: 'DEADLINE', title: overdue ? 'Report overdue' : 'Report due soon', targetType: 'PLACEMENT', targetId: placement.id, reportingPeriodId: period.id, dedupeKey: key }); } catch { /* unique key arbitrates replicas */ } } } }

  private async saveDraft(report: WeeklyReport, body: any, p: Principal, placement: Placement) { if (body.reportingPeriodId && body.reportingPeriodId !== report.reportingPeriodId) throw new BadRequestException('Reporting period is immutable'); const ids: string[] = body.attachmentDocumentIds ?? []; if (new Set(ids).size !== ids.length || ids.length > 10) throw new BadRequestException('Invalid attachments'); if (ids.length !== await this.documents.countBy({ id: In(ids), ownerUserId: p.id, state: 'AVAILABLE' })) throw new BadRequestException('Attachments must be owned available documents'); Object.assign(report, { draftAccomplishments: body.accomplishments ?? '', draftChallenges: body.challenges ?? '', draftNextWeekPlan: body.nextWeekPlan ?? '', draftSavedAt: new Date() }); await this.reports.save(report); await this.draftDocs.delete({ reportId: report.id }); if (ids.length) await this.draftDocs.save(ids.map((documentId) => ({ reportId: report.id, documentId }))); return this.reportDto(report, placement, true); }
  private async reportDto(report: WeeklyReport, placement: Placement, owner: boolean) { const period = await this.periods.findOneByOrFail({ id: report.reportingPeriodId }); const versions = await this.versions.find({ where: { reportId: report.id }, order: { versionNo: 'ASC' } }); const reviews = versions.length ? await this.reviews.findBy({ reportVersionId: In(versions.map((x) => x.id)) }) : []; const dto: any = { id: report.id, placementId: report.placementId, reportingPeriodId: report.reportingPeriodId, weekStart: period.weekStart, weekEnd: period.weekEnd, dueAt: period.dueAt, state: report.state, currentVersionNo: report.currentVersionNo, versions, reviews }; if (owner && report.draftSavedAt) dto.draft = { reportingPeriodId: report.reportingPeriodId, accomplishments: report.draftAccomplishments, challenges: report.draftChallenges, nextWeekPlan: report.draftNextWeekPlan, attachmentDocumentIds: (await this.draftDocs.findBy({ reportId: report.id })).map((x) => x.documentId) }; return dto; }
  private async placementAccess(p: Principal, id: string) { const placement = await this.placements.findOneBy({ id }); if (!placement) throw new NotFoundException(); if (p.role === 'ADMIN' || (p.role === 'STUDENT' && placement.studentId === p.id)) return placement; if (p.role === 'SUPERVISOR') { const a = await this.assignments.findOneBy({ placementId: id, supervisorUserId: p.id, revokedAt: null as any }); assert(a); return placement; } await this.companyAccess(p, placement.companyId); return placement; }
  private async companyAccess(p: Principal, companyId?: string) { if (p.role === 'ADMIN') return; const company = companyId ? await this.companies.findOneBy({ id: companyId }) : null; assert(p.role === 'COMPANY_STAFF' && Boolean(company?.staffUserIds.includes(p.id))); }
  private async assertSupervisor(id: string) { const [user, profile] = await Promise.all([this.users.findOneBy({ id }), this.supervisorProfiles.findOneBy({ userId: id })]); if (!user?.roles.includes('SUPERVISOR') || !profile) throw new BadRequestException('Supervisor is not eligible'); }
  private async documentAccess(p: Principal, id: string) { const doc = await this.documents.findOneBy({ id, state: 'AVAILABLE' }); if (!doc) throw new NotFoundException(); if (doc.ownerUserId === p.id) return doc; const draft = await this.draftDocs.findOneBy({ documentId: id }); if (draft) { const report = await this.reports.findOneBy({ id: draft.reportId }); if (report) await this.placementAccess(p, report.placementId); } const linked = await this.versionDocs.findOneBy({ documentId: id }); if (!linked) throw new NotFoundException(); const version = await this.versions.findOneBy({ id: linked.reportVersionId }); if (!version) throw new NotFoundException(); await this.placementAccess(p, (await this.reports.findOneByOrFail({ id: version.reportId })).placementId); return doc; }
  private documentDto(doc: Document) { const { objectKey: _key, ownerUserId: _owner, ...safe } = doc; return safe; }
  private jobDto(job: AiJob, _p: Principal) { const { inputSnapshot: _snapshot, ...safe } = job; return { ...safe, advisory: true, calculationVersion: job.kind === 'MATCH_EXPLANATION' ? 'skill-v1' : undefined, sourceChanged: job.kind === 'MATCH_EXPLANATION' ? false : undefined }; }
  private paginate<T>(items: T[], current?: string, perPage?: string) { const p = page(current), s = size(perPage); return { items: items.slice((p - 1) * s, p * s), page: p, pageSize: s, total: items.length }; }
}
function signatureMatches(bytes: Buffer, type: string) { if (type === 'application/pdf') return bytes.subarray(0, 5).toString() === '%PDF-'; if (type === 'image/jpeg') return bytes.subarray(0, 3).equals(Buffer.from([0xff, 0xd8, 0xff])); if (type === 'image/png') return bytes.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10])); return type.includes('wordprocessingml') && bytes.subarray(0, 4).equals(Buffer.from([0x50, 0x4b, 0x03, 0x04])); }
function countBy(rows: any[], field: string) { return rows.reduce((out, row) => ({ ...out, [row[field]]: (out[row[field]] ?? 0) + 1 }), {} as Record<string, number>); }
