import { Body, ConflictException, Controller, Get, NotFoundException, Param, Patch, Post, Put, Delete, Query, UseGuards, BadRequestException } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import { InjectRepository } from '@nestjs/typeorm';
import * as bcrypt from 'bcrypt';
import { DataSource, In, Repository } from 'typeorm';
import { Application, ApplicationDocument, ApplicationHistory, AuthSession, Company, Document, Notification, Placement, Posting, ReportingPeriod, SavedPosting, StudentProfile, SupervisorAssignment, SupervisorProfile, Task, User } from '../infrastructure/database/entities';
import { reportingPeriods } from './calendar';
import { assert, CurrentUser, Principal, Public, Roles, SessionGuard } from './auth';
import { calculateMatchScore, canTransitionApplication } from './core-domain';
import { SchedulerHealthService } from './scheduler-health.service';

@Controller('auth') export class AuthController {
  constructor(@InjectRepository(User) private users: Repository<User>, @InjectRepository(AuthSession) private sessions: Repository<AuthSession>, private jwt: JwtService) {}
  private async token(user: User, session: AuthSession) { const accessToken = await this.jwt.signAsync({ id: user.id, sid: session.id, role: session.activeRole, version: session.version, roles: user.roles }); return { accessToken, tokenType: 'Bearer', user: { id: user.id, email: user.email, fullName: user.fullName, roles: user.roles }, activeRole: session.activeRole }; }
  @Post('sign-in') @Public() async signIn(@Body() body: { email: string; password: string; activeRole?: string }) { const user = await this.users.findOneBy({ email: body.email?.trim().toLowerCase() }); if (!user || !(await bcrypt.compare(body.password ?? '', user.passwordHash))) throw new BadRequestException('Invalid email or password'); const role = (body.activeRole ?? user.roles[0]) as any; if (!user.roles.includes(role)) throw new BadRequestException('Role is not assigned to this user'); const session = await this.sessions.save({ userId: user.id, activeRole: role, version: 1, expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7) }); return this.token(user, session); }
  @Post('refresh') @Public() async refresh(@Body() body: { token: string }) { let p: Principal; try { p = await this.jwt.verifyAsync(body.token); } catch { throw new BadRequestException('Invalid token'); } const [user, session] = await Promise.all([this.users.findOneBy({ id: p.id }), this.sessions.findOneBy({ id: p.sid })]); if (!user || !session || session.revokedAt || session.version !== p.version) throw new BadRequestException('Expired session'); return this.token(user, session); }
  @Post('sign-out') @UseGuards(SessionGuard) async signOut(@CurrentUser() p: Principal) { await this.sessions.update(p.sid, { revokedAt: new Date() }); return { ok: true }; }
}

@Controller() export class CoreController {
  constructor(@InjectRepository(User) private users: Repository<User>, @InjectRepository(AuthSession) private sessions: Repository<AuthSession>, @InjectRepository(StudentProfile) private profiles: Repository<StudentProfile>, @InjectRepository(Company) private companies: Repository<Company>, @InjectRepository(Posting) private postings: Repository<Posting>, @InjectRepository(SavedPosting) private saved: Repository<SavedPosting>, @InjectRepository(Application) private applications: Repository<Application>, @InjectRepository(ApplicationDocument) private applicationDocs: Repository<ApplicationDocument>, @InjectRepository(ApplicationHistory) private history: Repository<ApplicationHistory>, @InjectRepository(Placement) private placements: Repository<Placement>, @InjectRepository(Task) private tasks: Repository<Task>, @InjectRepository(Notification) private notifications: Repository<Notification>, @InjectRepository(SupervisorProfile) private supervisorProfiles: Repository<SupervisorProfile>, @InjectRepository(SupervisorAssignment) private assignments: Repository<SupervisorAssignment>, @InjectRepository(ReportingPeriod) private periods: Repository<ReportingPeriod>, private jwt: JwtService, private dataSource: DataSource, private schedulerHealth: SchedulerHealthService) {}
  @Get('health') @Public() health() { const scheduler = this.schedulerHealth.snapshot(); return { status: scheduler.fresh ? 'ok' : 'degraded', scheduler }; }
  @Get('me') me(@CurrentUser() p: Principal) { return { id: p.id, roles: p.roles, activeRole: p.role }; }
  @Put('me/active-role') async setRole(@CurrentUser() p: Principal, @Body() body: { role: any }) { assert(p.roles.includes(body.role)); const session = await this.sessions.findOneByOrFail({ id: p.sid }); if (session.activeRole !== body.role) { session.activeRole = body.role; session.version++; await this.sessions.save(session); } return { activeRole: session.activeRole, accessToken: await this.jwt.signAsync({ id: p.id, sid: p.sid, role: session.activeRole, version: session.version, roles: p.roles }) }; }
  @Get('students/me') @Roles('STUDENT') async getMyProfile(@CurrentUser() p: Principal) { return (await this.profiles.findOneBy({ userId: p.id })) ?? this.profiles.save({ userId: p.id, skills: [], preferences: {} }); }
  @Patch('students/me') @Roles('STUDENT') async updateProfile(@CurrentUser() p: Principal, @Body() body: Partial<StudentProfile>) { const profile = (await this.profiles.findOneBy({ userId: p.id })) ?? this.profiles.create({ userId: p.id, skills: [], preferences: {} }); Object.assign(profile, body, { userId: p.id }); return this.profiles.save(profile); }
  @Get('students/me/skills') @Roles('STUDENT') async getSkills(@CurrentUser() p: Principal) { return (await this.getProfile(p)).skills; }
  @Put('students/me/skills') @Roles('STUDENT') async setSkills(@CurrentUser() p: Principal, @Body() body: { skills: StudentProfile['skills'] }) { const profile = await this.getProfile(p); profile.skills = body.skills ?? []; return (await this.profiles.save(profile)).skills; }
  @Get('students/me/preferences') @Roles('STUDENT') async getPreferences(@CurrentUser() p: Principal) { return (await this.getProfile(p)).preferences; }
  @Put('students/me/preferences') @Roles('STUDENT') async setPreferences(@CurrentUser() p: Principal, @Body() body: object) { const profile = await this.getProfile(p); profile.preferences = body; return (await this.profiles.save(profile)).preferences; }
  @Get('companies') async listCompanies() { return this.companies.find(); }
  @Get('companies/:id') async company(@Param('id') id: string) { const c = await this.companies.findOneBy({ id }); if (!c) throw new NotFoundException(); return c; }
  @Patch('companies/:id') @Roles('COMPANY_STAFF', 'ADMIN') async updateCompany(@CurrentUser() p: Principal, @Param('id') id: string, @Body() body: Partial<Company>) { const company = await this.companies.findOneBy({ id }); if (!company) throw new NotFoundException(); assert(p.role === 'ADMIN' || company.staffUserIds.includes(p.id)); Object.assign(company, body, { id: company.id, staffUserIds: company.staffUserIds }); return this.companies.save(company); }
  @Get('postings') async listPostings(@CurrentUser() p: Principal, @Query('includeUnavailable') unavailable?: string) { const rows = await this.postings.find({ order: { createdAt: 'DESC' } }); const available = rows.filter((x) => p.role !== 'STUDENT' || (x.status === 'OPEN' && x.applicationDeadline >= new Date().toISOString().slice(0, 10))); if (p.role === 'STUDENT') { const profile = await this.getProfile(p); return available.map((x) => ({ ...x, match: calculateMatchScore(profile.skills.map((s) => s.id), x.skills) })); } return unavailable === 'true' ? rows : available; }
  @Post('postings') @Roles('COMPANY_STAFF', 'ADMIN') async createPosting(@CurrentUser() p: Principal, @Body() body: Partial<Posting> & { companyId: string }) { const company = await this.companies.findOneBy({ id: body.companyId }); if (!company) throw new NotFoundException('Company not found'); assert(p.role === 'ADMIN' || company.staffUserIds.includes(p.id)); return this.postings.save(this.postings.create({ ...body, status: 'DRAFT', skills: body.skills ?? [], createdByUserId: p.id } as Posting)); }
  @Get('postings/saved') @Roles('STUDENT') async savedPostings(@CurrentUser() p: Principal) { const saved = await this.saved.findBy({ studentId: p.id }); return this.postings.findByIds(saved.map((x) => x.postingId)); }
  @Get('postings/:id') async getPosting(@CurrentUser() p: Principal, @Param('id') id: string) { const x = await this.postings.findOneBy({ id }); if (!x) throw new NotFoundException(); if (p.role === 'STUDENT' && (x.status !== 'OPEN' || x.applicationDeadline < new Date().toISOString().slice(0, 10))) throw new NotFoundException(); if (p.role === 'STUDENT') return { ...x, match: calculateMatchScore((await this.getProfile(p)).skills.map((s) => s.id), x.skills) }; return x; }
  @Patch('postings/:id') @Roles('COMPANY_STAFF', 'ADMIN') async updatePosting(@CurrentUser() p: Principal, @Param('id') id: string, @Body() body: Partial<Posting>) { const x = await this.postings.findOneBy({ id }); if (!x) throw new NotFoundException(); await this.assertPostingManager(p, x); if (x.status === 'ARCHIVED') throw new ConflictException('Archived posting cannot change'); Object.assign(x, body, { id: x.id, companyId: x.companyId, createdByUserId: x.createdByUserId }); return this.postings.save(x); }
  @Post('postings/:id/publish') @Roles('COMPANY_STAFF', 'ADMIN') async publish(@CurrentUser() p: Principal, @Param('id') id: string) { const x = await this.postings.findOneBy({ id }); if (!x) throw new NotFoundException(); await this.assertPostingManager(p, x); if (x.status !== 'DRAFT' || !x.title || !x.description || !Array.isArray(x.skills)) throw new ConflictException('Posting is incomplete'); x.status = 'OPEN'; return this.postings.save(x); }
  @Post('postings/:id/lifecycle') @Roles('COMPANY_STAFF', 'ADMIN') async postingLifecycle(@CurrentUser() p: Principal, @Param('id') id: string, @Body() body: { status: string }) { const x = await this.postings.findOneBy({ id }); if (!x) throw new NotFoundException(); await this.assertPostingManager(p, x); if (!((x.status === 'OPEN' && body.status === 'CLOSED') || (x.status === 'CLOSED' && body.status === 'ARCHIVED'))) throw new ConflictException('Invalid lifecycle transition'); x.status = body.status; return this.postings.save(x); }
  @Put('postings/:id/saved') @Roles('STUDENT') async savePosting(@CurrentUser() p: Principal, @Param('id') id: string) { const x = await this.postings.findOneBy({ id }); if (!x || x.status !== 'OPEN' || x.applicationDeadline < new Date().toISOString().slice(0, 10)) throw new ConflictException('Posting unavailable'); await this.saved.upsert({ studentId: p.id, postingId: id }, ['studentId', 'postingId']); return { saved: true }; }
  @Delete('postings/:id/saved') @Roles('STUDENT') async unsave(@CurrentUser() p: Principal, @Param('id') id: string) { await this.saved.delete({ studentId: p.id, postingId: id }); return { saved: false }; }
  @Post('applications') @Roles('STUDENT') async apply(@CurrentUser() p: Principal, @Body() body: { postingId: string; coverNote: string; contactName?: string; contactEmail?: string; university?: string; major?: string; availability?: string; cvDocumentId?: string; supportingDocumentIds?: string[]; [key: string]: unknown }) { const required = [body.coverNote, body.contactName, body.contactEmail, body.university, body.major, body.availability]; if (required.some(x => !String(x ?? '').trim()) || !body.cvDocumentId) throw new BadRequestException('Application contact, education, availability, coverNote and CV are required'); const attachmentIds = body.supportingDocumentIds ?? []; if (new Set(attachmentIds).size !== attachmentIds.length) throw new BadRequestException('Duplicate supporting documents'); return this.dataSource.transaction(async manager => { const posting = await manager.getRepository(Posting).createQueryBuilder('p').setLock('pessimistic_write').where('p.id = :id', { id: body.postingId }).getOne(); if (!posting || posting.status !== 'OPEN' || posting.applicationDeadline < new Date().toISOString().slice(0, 10)) throw new ConflictException('Posting unavailable'); const ids = [body.cvDocumentId!, ...attachmentIds]; if (ids.length !== await manager.getRepository(Document).countBy({ id: In(ids), ownerUserId: p.id, state: 'AVAILABLE' })) throw new BadRequestException('Application documents must be owned and available'); try { const application = await manager.getRepository(Application).save({ studentId: p.id, postingId: body.postingId, cvDocumentId: body.cvDocumentId, coverNote: body.coverNote.trim(), snapshot: { ...body, supportingDocumentIds: attachmentIds } }); await manager.getRepository(ApplicationDocument).save(attachmentIds.map(documentId => ({ applicationId: application.id, documentId, kind: 'SUPPORTING' }))); await manager.getRepository(ApplicationHistory).save({ applicationId: application.id, toStatus: 'SUBMITTED', actorUserId: p.id }); return application; } catch (error: any) { if (error?.code === '23505') throw new ConflictException('Application already exists'); throw error; } }); }
  @Get('applications') async listApplications(@CurrentUser() p: Principal) { if (p.role === 'STUDENT') return this.applications.findBy({ studentId: p.id }); if (p.role === 'ADMIN') return this.applications.find(); const companies = await this.companies.find(); const postingIds = (await this.postings.find()).filter((x) => companies.some((c) => c.id === x.companyId && c.staffUserIds.includes(p.id))).map((x) => x.id); return this.applications.createQueryBuilder('a').where('a.posting_id IN (:...ids)', { ids: postingIds.length ? postingIds : ['00000000-0000-0000-0000-000000000000'] }).getMany(); }
  @Get('applications/:id') async getApplication(@CurrentUser() p: Principal, @Param('id') id: string) { const app = await this.applications.findOneBy({ id }); if (!app) throw new NotFoundException(); await this.assertApplicationAccess(p, app); return { ...app, history: await this.history.find({ where: { applicationId: id }, order: { changedAt: 'ASC' } }) }; }
  @Post('applications/:id/withdraw') @Roles('STUDENT') async withdraw(@CurrentUser() p: Principal, @Param('id') id: string, @Body() body: { note?: string }) { return this.transitionApplication(p, id, 'WITHDRAWN', body.note); }
  @Post('applications/:id/status') @Roles('COMPANY_STAFF', 'ADMIN') async status(@CurrentUser() p: Principal, @Param('id') id: string, @Body() body: { status: string; note?: string; supervisorUserId?: string; startDate?: string; endDate?: string }) { if (body.status === 'ACCEPTED') return this.acceptApplication(p, id, body); return this.transitionApplication(p, id, body.status, body.note); }
  @Get('placements') async listPlacements(@CurrentUser() p: Principal) { if (p.role === 'STUDENT') return this.placements.findBy({ studentId: p.id }); if (p.role === 'SUPERVISOR') return this.placements.findBy({ supervisorUserId: p.id }); return this.placements.find(); }
  @Get('placements/:id') async getPlacement(@CurrentUser() p: Principal, @Param('id') id: string) { const placement = await this.placements.findOneBy({ id }); if (!placement) throw new NotFoundException(); await this.assertPlacementAccess(p, placement); return placement; }
  @Post('placements/:id/lifecycle') @Roles('SUPERVISOR', 'ADMIN') async placementLifecycle(@CurrentUser() p: Principal, @Param('id') id: string, @Body() body: { status: string }) { const placement = await this.getPlacement(p, id); if (placement.status !== 'ACTIVE' || !['COMPLETED', 'TERMINATED'].includes(body.status)) throw new ConflictException('Invalid lifecycle transition'); placement.status = body.status; return this.placements.save(placement); }
  @Get('placements/:id/tasks') async getTasks(@CurrentUser() p: Principal, @Param('id') id: string) { await this.getPlacement(p, id); return this.tasks.findBy({ placementId: id }); }
  @Post('placements/:id/tasks') @Roles('SUPERVISOR', 'ADMIN') async createTask(@CurrentUser() p: Principal, @Param('id') id: string, @Body() body: { title: string; description: string; priority: string; dueDate?: string }) { const placement = await this.getPlacement(p, id); if (placement.status !== 'ACTIVE' || !body.title?.trim() || !body.description?.trim()) throw new BadRequestException('Active placement, title and description are required'); const task = await this.tasks.save({ placementId: id, title: body.title.trim(), description: body.description.trim(), priority: body.priority, dueDate: body.dueDate, status: 'TODO' }); await this.notifications.save({ recipientUserId: placement.studentId, type: 'TASK_ASSIGNED', title: 'New placement task', targetId: task.id }); return task; }
  @Patch('placements/:id/tasks/:taskId/status') @Roles('STUDENT') async taskStatus(@CurrentUser() p: Principal, @Param('id') id: string, @Param('taskId') taskId: string, @Body() body: { status: string }) { const placement = await this.getPlacement(p, id); if (placement.studentId !== p.id || placement.status !== 'ACTIVE' || !['TODO', 'IN_PROGRESS', 'DONE'].includes(body.status)) throw new ConflictException('Task cannot be changed'); const task = await this.tasks.findOneBy({ id: taskId, placementId: id }); if (!task) throw new NotFoundException(); task.status = body.status; return this.tasks.save(task); }
  @Get('notifications') async listNotifications(@CurrentUser() p: Principal) { return this.notifications.find({ where: { recipientUserId: p.id }, order: { createdAt: 'DESC' } }); }
  @Post('notifications/:id/read') async readNotification(@CurrentUser() p: Principal, @Param('id') id: string) { const notification = await this.notifications.findOneBy({ id, recipientUserId: p.id }); if (!notification) throw new NotFoundException(); notification.readAt = new Date(); return this.notifications.save(notification); }
  @Post('notifications/mark-read') async readAll(@CurrentUser() p: Principal) { await this.notifications.createQueryBuilder().update().set({ readAt: new Date() }).where('recipient_user_id = :id AND read_at IS NULL', { id: p.id }).execute(); return { ok: true }; }
  private async getProfile(p: Principal) { return (await this.profiles.findOneBy({ userId: p.id })) ?? this.profiles.save({ userId: p.id, skills: [], preferences: {} }); }
  private async assertPostingManager(p: Principal, posting: Posting) { if (p.role === 'ADMIN') return; const company = await this.companies.findOneBy({ id: posting.companyId }); assert(company?.staffUserIds.includes(p.id)); }
  private async assertApplicationAccess(p: Principal, app: Application) { if (p.role === 'ADMIN' || (p.role === 'STUDENT' && app.studentId === p.id)) return; const posting = await this.postings.findOneBy({ id: app.postingId }); if (p.role === 'COMPANY_STAFF' && posting) return this.assertPostingManager(p, posting); const placement = await this.placements.findOneBy({ applicationId: app.id }); assert(p.role === 'SUPERVISOR' && placement?.supervisorUserId === p.id); }
  private async assertPlacementAccess(p: Principal, placement: Placement) { if (p.role === 'ADMIN' || (p.role === 'STUDENT' && placement.studentId === p.id) || (p.role === 'SUPERVISOR' && placement.supervisorUserId === p.id)) return; const company = await this.companies.findOneBy({ id: placement.companyId }); assert(p.role === 'COMPANY_STAFF' && company?.staffUserIds.includes(p.id)); }
  private async acceptApplication(p: Principal, id: string, body: { supervisorUserId?: string; startDate?: string; endDate?: string; note?: string }) {
    if (!body.supervisorUserId || !body.startDate || !body.endDate || body.endDate < body.startDate) throw new BadRequestException('Acceptance needs supervisor and ordered dates'); const command = { supervisorUserId: body.supervisorUserId, startDate: body.startDate, endDate: body.endDate, note: body.note?.trim() || null };
    return this.dataSource.transaction(async manager => {
      const apps = manager.getRepository(Application); const app = await apps.createQueryBuilder('a').setLock('pessimistic_write').where('a.id = :id', { id }).getOne(); if (!app) throw new NotFoundException();
      const posting = await manager.getRepository(Posting).findOneBy({ id: app.postingId }); if (!posting) throw new NotFoundException(); if (p.role !== 'ADMIN') { const company = await manager.getRepository(Company).findOneBy({ id: posting.companyId }); assert(company?.staffUserIds.includes(p.id)); }
      const history = manager.getRepository(ApplicationHistory); const placementRepo = manager.getRepository(Placement); const prior = await history.findOne({ where: { applicationId: id, toStatus: 'ACCEPTED' } }); const existing = await placementRepo.findOneBy({ applicationId: id });
      if (app.status === 'ACCEPTED') { if (existing && JSON.stringify(prior?.acceptanceCommand ?? null) === JSON.stringify(command)) return { application: app, placement: existing }; throw new ConflictException('ACCEPTANCE_CONFLICT'); }
      if (app.status !== 'INTERVIEW') throw new ConflictException('Invalid application transition'); const supervisor = await manager.getRepository(User).findOneBy({ id: command.supervisorUserId }); const profile = await manager.getRepository(SupervisorProfile).findOneBy({ userId: command.supervisorUserId }); if (!supervisor?.roles.includes('SUPERVISOR') || !profile) throw new BadRequestException('Supervisor is not eligible');
      app.status = 'ACCEPTED'; await apps.save(app); await history.save({ applicationId: app.id, fromStatus: 'INTERVIEW', toStatus: 'ACCEPTED', actorUserId: p.id, note: command.note ?? undefined, acceptanceCommand: command });
      const placement = await placementRepo.save({ applicationId: app.id, studentId: app.studentId, postingId: posting.id, companyId: posting.companyId, supervisorUserId: command.supervisorUserId, startDate: command.startDate, endDate: command.endDate, status: 'ACTIVE', reportingTimezone: 'Asia/Ho_Chi_Minh' }); await manager.getRepository(SupervisorAssignment).save({ placementId: placement.id, supervisorUserId: command.supervisorUserId, assignedByUserId: p.id, reason: command.note ?? undefined }); await manager.getRepository(ReportingPeriod).save(reportingPeriods(command.startDate, command.endDate, placement.reportingTimezone).map(x => ({ placementId: placement.id, ...x }))); await manager.getRepository(Notification).save({ recipientUserId: app.studentId, type: 'APPLICATION_STATUS_CHANGED', title: 'Application accepted', targetType: 'APPLICATION', targetId: app.id }); return { application: app, placement };
    });
  }
  private async transitionApplication(p: Principal, id: string, to: string, note?: string) { const app = await this.applications.findOneBy({ id }); if (!app) throw new NotFoundException(); await this.assertApplicationAccess(p, app); const actor = p.role === 'STUDENT' ? 'student' : 'staff'; if (!canTransitionApplication(app.status as any, to as any, actor)) throw new ConflictException('Invalid application transition'); const from = app.status; app.status = to; await this.applications.save(app); await this.history.save({ applicationId: id, fromStatus: from, toStatus: to, actorUserId: p.id, note: note?.trim() || undefined }); if (to !== 'WITHDRAWN') await this.notifications.save({ recipientUserId: app.studentId, type: 'APPLICATION_STATUS', title: `Application ${to.replace('_', ' ').toLowerCase()}`, targetId: id }); return app; }
}
