import { Column, CreateDateColumn, Entity, Index, JoinColumn, ManyToOne, OneToMany, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm';

export type Role = 'STUDENT' | 'COMPANY_STAFF' | 'SUPERVISOR' | 'ADMIN';
@Entity('users') export class User { @PrimaryGeneratedColumn('uuid') id!: string; @Column({ unique: true }) email!: string; @Column({ name: 'password_hash' }) passwordHash!: string; @Column({ name: 'full_name' }) fullName!: string; @Column({ nullable: true }) phone?: string; @Column('simple-array', { default: '' }) roles!: Role[]; @CreateDateColumn({ name: 'created_at' }) createdAt!: Date; @UpdateDateColumn({ name: 'updated_at' }) updatedAt!: Date; }
@Entity('auth_sessions') export class AuthSession { @PrimaryGeneratedColumn('uuid') id!: string; @Column({ name: 'user_id' }) userId!: string; @Column({ name: 'active_role' }) activeRole!: Role; @Column({ default: 1 }) version!: number; @Column({ name: 'expires_at', type: 'timestamptz' }) expiresAt!: Date; @Column({ name: 'revoked_at', type: 'timestamptz', nullable: true }) revokedAt?: Date; }
@Entity('student_profiles') export class StudentProfile { @PrimaryGeneratedColumn('uuid') id!: string; @Index({ unique: true }) @Column({ name: 'user_id' }) userId!: string; @Column({ nullable: true }) university?: string; @Column({ nullable: true }) major?: string; @Column({ name: 'graduation_year', nullable: true }) graduationYear?: number; @Column({ nullable: true }) bio?: string; @Column('jsonb', { default: [] }) skills!: { id: string; name: string; proficiency?: string }[]; @Column('jsonb', { default: {} }) preferences!: object; @UpdateDateColumn({ name: 'updated_at' }) updatedAt!: Date; }
@Entity('companies') export class Company { @PrimaryGeneratedColumn('uuid') id!: string; @Index({ unique: true }) @Column() name!: string; @Column({ nullable: true }) website?: string; @Column({ nullable: true }) industry?: string; @Column({ nullable: true }) description?: string; @Column('simple-array', { name: 'staff_user_ids', default: '' }) staffUserIds!: string[]; @CreateDateColumn({ name: 'created_at' }) createdAt!: Date; @UpdateDateColumn({ name: 'updated_at' }) updatedAt!: Date; }
@Entity('postings') export class Posting { @PrimaryGeneratedColumn('uuid') id!: string; @Column({ name: 'company_id' }) companyId!: string; @Column() title!: string; @Column() description!: string; @Column({ nullable: true }) category?: string; @Column({ nullable: true }) location?: string; @Column({ name: 'work_arrangement' }) workArrangement!: string; @Column({ name: 'duration_weeks', type: 'int' }) durationWeeks!: number; @Column({ type: 'int' }) openings!: number; @Column({ name: 'application_deadline', type: 'date' }) applicationDeadline!: string; @Column({ default: 'DRAFT' }) status!: string; @Column('jsonb', { default: [] }) skills!: { id: string; name: string; importance: 'REQUIRED' | 'OPTIONAL' }[]; @Column({ name: 'created_by_user_id' }) createdByUserId!: string; @CreateDateColumn({ name: 'created_at' }) createdAt!: Date; @UpdateDateColumn({ name: 'updated_at' }) updatedAt!: Date; }
@Entity('saved_postings') @Index(['studentId', 'postingId'], { unique: true }) export class SavedPosting { @PrimaryGeneratedColumn('uuid') id!: string; @Column({ name: 'student_id' }) studentId!: string; @Column({ name: 'posting_id' }) postingId!: string; @CreateDateColumn({ name: 'saved_at' }) savedAt!: Date; }
@Entity('applications') @Index(['studentId', 'postingId'], { unique: true }) export class Application { @PrimaryGeneratedColumn('uuid') id!: string; @Column({ name: 'student_id' }) studentId!: string; @Column({ name: 'posting_id' }) postingId!: string; @Column({ default: 'SUBMITTED' }) status!: string; @Column('jsonb') snapshot!: object; @Column({ name: 'cover_note' }) coverNote!: string; @CreateDateColumn({ name: 'submitted_at' }) submittedAt!: Date; @UpdateDateColumn({ name: 'updated_at' }) updatedAt!: Date; }
@Entity('application_status_history') export class ApplicationHistory { @PrimaryGeneratedColumn('uuid') id!: string; @Column({ name: 'application_id' }) applicationId!: string; @Column({ name: 'from_status', nullable: true }) fromStatus?: string; @Column({ name: 'to_status' }) toStatus!: string; @Column({ name: 'actor_user_id' }) actorUserId!: string; @Column({ nullable: true }) note?: string; @CreateDateColumn({ name: 'changed_at' }) changedAt!: Date; }
@Entity('placements') export class Placement { @PrimaryGeneratedColumn('uuid') id!: string; @Index({ unique: true }) @Column({ name: 'application_id' }) applicationId!: string; @Column({ name: 'student_id' }) studentId!: string; @Column({ name: 'posting_id' }) postingId!: string; @Column({ name: 'company_id' }) companyId!: string; @Column({ name: 'supervisor_user_id' }) supervisorUserId!: string; @Column({ name: 'start_date', type: 'date' }) startDate!: string; @Column({ name: 'end_date', type: 'date' }) endDate!: string; @Column({ default: 'ACTIVE' }) status!: string; @CreateDateColumn({ name: 'created_at' }) createdAt!: Date; }
@Entity('tasks') export class Task { @PrimaryGeneratedColumn('uuid') id!: string; @Column({ name: 'placement_id' }) placementId!: string; @Column() title!: string; @Column() description!: string; @Column() priority!: string; @Column({ name: 'due_date', type: 'date', nullable: true }) dueDate?: string; @Column({ default: 'TODO' }) status!: string; @CreateDateColumn({ name: 'created_at' }) createdAt!: Date; }
@Entity('notifications') export class Notification { @PrimaryGeneratedColumn('uuid') id!: string; @Column({ name: 'recipient_user_id' }) recipientUserId!: string; @Column() type!: string; @Column() title!: string; @Column({ nullable: true }) body?: string; @Column({ name: 'target_id', nullable: true }) targetId?: string; @Column({ name: 'read_at', type: 'timestamptz', nullable: true }) readAt?: Date; @CreateDateColumn({ name: 'created_at' }) createdAt!: Date; }
export const entities = [User, AuthSession, StudentProfile, Company, Posting, SavedPosting, Application, ApplicationHistory, Placement, Task, Notification];
